# Numpy <hr style="border:2.5px solid #ad0000ff"></hr>

<b>Ivan Paul J. Untaran</b>
<br>Computer Engineer

In [137]:
#i imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [138]:
my_array = [1,2,3]

In [139]:
type(my_array)

list

In [140]:
my_array = np.array([1,2,3])

In [141]:
np.shape(my_array)

(3,)

# 2D Array

In [142]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])

In [143]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
np.shape(my_array)

(2, 3)

In [145]:
trans_array = my_array.T

In [146]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [147]:
np.shape(trans_array)

(3, 2)

In [148]:
np.sum(trans_array, axis = 0)

array([ 6, 15])

In [149]:
np.sum(trans_array, axis = 1)

array([5, 7, 9])

# Measure of Central Tendency

In [150]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3.9, 8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])


In [151]:
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3.9,  8. ],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [152]:
np.mean(resistance, axis = 1)

array([9.31818182,        nan])

In [153]:
np.mean(resistance, axis = 0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.5 ,   nan])

In [154]:
np.nanmean(resistance, axis = 1)

array([ 9.31818182, 10.75      ])

In [155]:
jag_mean = np.nanmean(resistance, axis = 1)[0]
pan_mean = np.nanmean(resistance, axis = 1)[1]

print(f'Jaguar_mean = {jag_mean:.2f} omhs')
print(f'Panther_mean = {pan_mean:.2f} omhs')

Jaguar_mean = 9.32 omhs
Panther_mean = 10.75 omhs


In [156]:
np.nanmedian(resistance, axis = 1)

array([9.8 , 9.55])

In [157]:
jag_mean = np.nanmedian(resistance, axis = 1)[0]
pan_mean = np.nanmedian(resistance, axis = 1)[1]

print(f'Jaguar_mean = {jag_mean:.2f} omhs')
print(f'Panther_mean = {pan_mean:.2f} omhs')

Jaguar_mean = 9.80 omhs
Panther_mean = 9.55 omhs


In [158]:
stats.mode(resistance, axis = 1)

ModeResult(mode=array([10.4,  9.1]), count=array([2, 3]))

In [159]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [160]:
jag_res = resistance[0]
print("Jaguar mode:")
for i in multimode(jag_res):
    print(f'{i} in ohms')

Jaguar mode:
10.4 in ohms


In [161]:
pan_res = resistance[1]
print("Panther mode:")
for i in multimode(pan_res):
    print(f'{i} in ohms')

Panther mode:
9.1 in ohms


# Measures of Variability

In [162]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3.9, 8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])

resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3.9,  8. ],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [163]:
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 7.1, 10.9])

In [164]:
print(f'Jaguar_range = {res_range[0]:.2f} ohms')
print(f'Panther_range = {res_range[1]:.2f} ohms')

Jaguar_range = 7.10 ohms
Panther_range = 10.90 ohms


In [165]:
# 1st Quartile
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.2  , 9.125])

In [166]:
# 2nd Quartile
res_Q2 = np.nanpercentile(resistance, 50, axis=1)
res_Q2

array([9.8 , 9.55])

In [167]:
# 3rd Quartile
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3

array([10.45 , 10.625])

In [168]:
# IQR
print(f'Jaguar IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR = 1.25 ohms
Panther IQR = 1.50 ohms


In [169]:
# Variance
res_var = np.nanvar(resistance, ddof=1, axis=1)
res_var

array([ 3.96163636, 11.08277778])

In [170]:
print(f'Jaguar Variance = {res_var[0]:.2f} ohms')
print(f'Panther Variance = {res_var[1]:.2f} ohms')

Jaguar Variance = 3.96 ohms
Panther Variance = 11.08 ohms


In [ ]:
# Standard Deviation
res_std = np.nanstd(resistance, ddof=1, axis=1)
res_std

In [ ]:
print(f'Jaguar Standard Deviation = {res_std[0]:.2f} ohms')
print(f'Panther Standard Deviation = {res_std[1]:.2f} ohms')